Fix issues with running the RPi OS Lite installer.
Screenly/Anthias pull request #1799
Opened 2023-04-17 02:21 UTC by nicomiguelino

#### Overview

- Still a work in progress. I just added some `echo` statements to debug stuff.

2023-04-21 14:23 UTC, nicomiguelino commented
I got the following error after doing `modprobe` before `dist-upgrade`:

![image](https://user-images.githubusercontent.com/10234135/233660413-734a5fb4-86d7-4036-b1e4-0e3c30772d07.png)

Here's a copy-pastable version:

```
Error response from daemon: driver failed programming external connectivity on endpoint screenly-redis-1 (a029c6773774d539dd6e5fc6fda5fc0bb768d70d23c73ab8a9f2ae8fdd4263fe):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 127.0.0.1 --dport 6379 -j DNAT --to-destination 172.18.0.3:6379 ! -i br-655f692f21d3: iptables v1.8.7 (nf_tables): unknown option "--dport"                                                                                                          Try `iptables -h' or 'iptables --help' for more information.                                                                                                     (exit status 2))
```

2023-04-24 18:03 UTC, nicomiguelino commented on ansible/roles/system/tasks/main.yml
> +    sudo modprobe ip_tables
Since a reboot is really required for the Docker containers to start successfully, we won't be needing these anymore.

2023-04-25 07:35 UTC, vpetersson requested changes
Please remove the debug code

2023-04-27 09:33 UTC, vpetersson approved these changes

2023-04-27 15:51 UTC, merged